const fs = require('fs');
let data = fs.readFileSync('src/data.ts', 'utf-8');

const replacements = [
  ["sừng trâu tước thay Tê giác", "bột"],
  ["Mát xa đắp ấm quanh khớp sống lưng, các rễ tay để tăng máu tươi ngấm tụ, tránh vặn bẻ giật cục vì dễ nứt vi xương gãy mục.", "Xoa bóp, xát ấm quanh khớp và các chi để tăng tuần hoàn, tránh bẻ nắn thô bạo gây tổn thương hoặc gãy xương."],
  ["Trẻ lùn còi, não bé, thóp lâu liền, cổ ngửa mềm không giữ nổi đống, răng mọc thưa chậm, tay chân co rút yếu xoắn ríu vặn (Spasticity/Dystonia). Lưỡi thâm. Phản xạ bất thường.", "Trẻ chậm phát triển thể chất và tinh thần, thóp lâu liền, cổ mềm yếu, răng mọc chậm. Chi thể co cứng hoặc múa vờn. Chất lưỡi đỏ nhờn hoặc thâm tím. Tiểu tiện trong dài."],
  ["vào cốt tủy hun đốt tân dịch sinh chứng nhiệt cực sinh phong, gây tổn thương âm tinh vinh vệ đà tàn phá gân não.", "hao tổn âm dịch sinh nội nhiệt, nhiệt tà ẩn nấp gây chứng nội phong, làm tổn thương vinh vệ và gân mạch."],
  ["Cân nặng / tuổi < -3SD. Tay chân khẳng khiu xương bọc da, mất mô mỡ teo cơ mông. Rụng tóc, mặt nhăn nheo như khỉ khọm.", "Trẻ sụt cân nghiêm trọng, mất lớp mỡ dưới da ở mặt, mông, chi. Trẻ gầy mòn, cơ nhẽo, da nhăn nheo."],
  ["Bụng to ỏng chướng, gân xanh nổi ngoằn ngoèo, ấn thấy cứng hoặc có cục phân sán. Đầu tóc thưa, tay chân rụt chân chim teo, trằn trọc cắn xé quấy khóc, đi cầu chua phân nát. Rêu dày nhớt bẩn.", "Bụng trướng to, nổi tĩnh mạch xanh, sờ thấy cục tích trệ. Tóc thưa rụng, chi thể gầy mòn, hay quấy khóc, ngủ không yên, phân lỏng sống. Rêu lưỡi dày bẩn."],
  ["mở rỗng Tỳ để nuôi ruột hấp thu", "kiện tỳ tiêu thực, tống trệ"],
  ["Vétt nhéo dọc gân sống lưng 5 lần/ngày để kinh khí cường thăng, kích thích bú nuốt bạo ăn (Thủ thuật Nắn dọc hoa đà giáp tích).", "Sử dụng thủ thuật vuốt, nắn dọc hai bên cột sống (Hoa Đà giáp tích) để kiện Tỳ, tăng cường tiêu hoá cho trẻ."],
  ["Thấp nhiệt độc tà (Virus) xâm nhập phục lưu dật sâu vào kinh Can Đởm thời gian dài, làm khí tàn trệ, huyết ứ nghẹn sinh khối hòn báng bĩ, hao tổn Can Thận âm.", "Thấp nhiệt độc xâm nhập tạng Can, Đởm, lâu ngày làm khí trệ huyết ứ, sinh tích tụ khối cục, hao tổn Can Thận âm."],
  ["Nhiệt thấp uẩn độc, Đởm khí trào", "Thấp nhiệt uẩn kết, Đởm khí không sơ tiết"],
  ["xả mật tắc nghẽn thông thoát qua nước đái", "thanh nhiệt lợi thấp thoái hoàng"],
  ["Da mặt sạm nhọ, ngực có mạng nhện (sao mạch), gan bàn tay đỏ (lòng tay son). Mạng sườn phải có mảng cứng tức. Đêm khó ngủ bứt dứt trằn trọc ngứa. Nếu nặng thì chân phù cổ trướng nước.", "Da mặt xạm, xuất hiện sao mạch ở ngực, lòng bàn tay son. Mạng sườn phải ấn tức. Đêm khó ngủ, hay mẩn ngứa. Giai đoạn nặng có thể có cổ trướng phù chi."],
  ["Uất nhiệt tổn âm tinh, huyết mạch bế kết xơ tảng", "Tỳ khí hư, Can âm hư, Huyết lạc ứ trệ"],
  ["làm rã khối uất sậm", "nhuyễn kiên tán kết, tiêu trừ báng bĩ"],
  ["Ban sẩn đỏ tré, dầy cộm mài sắc, ban ngày dĩm lúc đêm ngủ chăn nóng ngứa phát rồ tịt đắp", "Ban sẩn phù màu đỏ, nổi cộm trên da, gặp nóng hoặc đắp chăn ấm thì ngứa tăng thêm, gãi nhiều"],
  ["nước đái gắt vàng", "tiểu tiện vàng sẻn"],
  ["hụp mát làm xẹp ban tấy tịt ngứa gắt", "dùng để thanh nhiệt, tiêu ban, giảm ngứa"],
  ["Nổi sẩn bạt màu nhợt buốt, ngứa đay lúc trời mưa lạnh gió buốt. Chờm nóng đắp mền thì ngứa lặn dần, ngâm nước lạnh đắp lại cục buốt ngứa cắn xé bì da.", "Ban sẩn phù có màu mờ nhạt, nổi nhiều khi thời tiết lạnh gió, chườm nóng ấm ngứa sẽ giảm, dính nước lạnh ngứa tăng dữ dội."],
  ["nóng hẩy ra cái mồ hôi dâm thì bão ngứa tan đè bọt", "ấm nôn mồ hôi nhẹ để tán phong hàn, chỉ dương"],
  ["Giã củ gừng nhỏ rang muối hột đắp xát lằn ngứa giúp hỏa ấm làm lui tà hàn phồng.", "Có thể dùng gừng tươi sao nóng với muối hạt chườm lên vùng biểu bì bị nổi sẩn để hỗ trợ ôn kinh tán hàn."],
  ["co cứng hoặc cổ bàng quang căng đúp không cho lọt được giọt tiểu ra ngoài, ứ căng vùng bụng dưới", "ứ trệ do cơ niệu đạo bàng quang co thắt, bàng quang căng đầy, tiểu không ra được"],
  ["Bệnh nhân vật vã ứ tiểu (Cầu bàng quang dương tính to lên tận rốn), nhưng không rặn đi được giọt nào. Do phì đại, viêm niệu hoặc sốc cơ năng sau đẻ/mổ.", "Người bệnh có cảm giác buồn tiểu nhiều nhưng không thể đi được. Cầu bàng quang căng to. Bí tiểu cơ năng thường gặp sau phẫu thuật, đẻ hoặc do phì đại tuyến tiền liệt."],
  ["giáng khí thủy thủy đạo tụ hãm", "kéo hãm, thủy dịch ứ trệ"],
  ["rặn bàng quang sức tống tạt", "trợ lực bàng quang bài tiết nước tiểu"],
  ["lòi búi trĩ mềm độ 1 đến 4 hậu môn, lúc ấn rát cộm. Khám thấy búi nhũn tụ máu.", "thấy búi trĩ sa ra ngoài hậu môn bầm tụ, gây cảm giác cộm rát."],
  ["ngồi ỳ làm dương hư Tỳ khí đi xuống hãm (Khí hư hãm) không co rút tĩnh mạch lên được. Hoặc ăn cay nóng táo bón sinh Thấp nhiệt dồn tụ đại trường lở nứt trĩ rỉ huyết.", "ngồi nhiều, đứng lâu, táo bón làm tổn thương cơ nhục, tỳ khí hư hãm không co nhiếp được, hoặc do ăn nhiều đồ cay nóng sinh thấp nhiệt dồn xuống đại trường gây xuất huyết, sưng đau."],
  ["chống lại táo bón, nằm võng đệm êm tránh xết trực tràng. Ăn nhuận tràng diếp cá mồng tơi.", "Duy trì chế độ ăn nhiều chất xơ (rau diếp cá, mồng tơi), uống nhiều nước, tập đại tiện đúng giờ, không ngồi xổm quá lâu."],
  ["Trĩ sa sưng đau, rát đỏ lừ sưng chói. Đi tiêu xong máu rỏ tươi chảy nhiễu từng giọt tỏng, táo bón rắn khô nứt toác. Lưỡi đỏ bầm rêu sẫm nhầy. Mạch hoạt sác.", "Búi trĩ sa sưng đau tấy đỏ lở loét. Đi ngoài ra máu tươi nhỏ giọt hoặc thành tia, táo bón phân khô cứng. Lưỡi đỏ, rêu vàng nhớt. Mạch hoạt sác."],
  ["mát tịt hậu môn ngọn lửa buốt", "lương huyết chỉ huyết, thanh nhiệt ở trực tràng đại trường"],
  ["mông teo búi viêm", "ngâm trực tiếp tại vùng hậu môn hằng ngày"],
  ["Trĩ lồi lòi tịt rốn rũ ra rã rời khi đi bộ, xích thụt đẩy không tự rụt mà phải lấy ngón tay nhét vào cựa. Sắc mặt bệch bệch mỏi nhọc đoản khí, phân lỏng nát dẻo giả đi xong sệp lại lòi. Mạch hư yếu tế.", "Búi trĩ sa hẳn ra ngoài, sa khi đi bộ, không tự co lên được phải dùng tay đẩy lên. Sắc mặt nhợt nhạt, mệt mỏi đoản hơi, phân lỏng. Mạch trầm nhược hoặc tế yếu."],
  ["không thăng chở sức đề hạ, cân mạch chùng rách", "hư không thăng thanh cử hãm được"],
  ["Rút cơ vòng co bóp nâng búi giãn lủng củng lên khoang trên.", "Thăng dương cử hãm, hỗ trợ nâng co búi trĩ hồi vị."],
  ["méo miệng, thất ngôn", "méo miệng, nói khó, thất ngôn"],
  ["Liệt nửa người không hoàn toàn hoặc hoàn toàn, nói khó ngọng. Không hôn mê, vẫn tỉnh táo (Trúng kinh lạc). Mặt nhợt nhạt, mệt mỏi, thở ngắn. Lưỡi bệu điểm ứ tía, rêu nhầy đàm. Mạch nhu tế nhược.", "Liệt nửa người hoàn toàn hoặc bán phần, nói khó hoặc ngọng, ý thức vẫn trọn vẹn (Trúng kinh lạc). Sắc mặt trắng bệch, mệt mỏi, đoản hơi. Chất lưỡi bệu nhợt có điểm ứ huyết, rêu nhày. Mạch hư nhược."],
  ["vỡ tung tạng phủ đè ép não tủy", "vọng hành xuất huyết nội tạng não"],
  ["Tuyệt đối kiểm soát HA và không để cáu giận xúc động cực độ", "Kiểm soát mỡ máu và huyết áp chặc chẽ, tránh xa các đợt xúc động cáu giận."],
  ["Đột nhiên ngã lăn hôn mê bất tỉnh nhân sự, hai hàm răng cắn chặt, hai tay nắm chặt, đại tiểu tiện bí bế không thông. Mặt đỏ bừng, thở khò khè mạnh đàm dãi lấp thanh quản.", "Đột nhiên hôn mê bất tỉnh, hai hàm răng cắn chặt, hai tay nắm chặt co quắp, đại tiểu tiện bí bế không thông. Mặt đỏ bừng, thở khò khè đàm dãi nhiều."],
  ["Hỏa ứ nhiệt phong bế khiếu", "Đàm nhiệt nội uẩn, Can phong nội động bế khiếu"],
  ["Xoa mài tán bột hòa nước ấm cạy miệng đổ rỏ giọt cấp cứu làm tinh thần tỉnh lại, tiêu máu bầm hỏa nhiệt. (Chỉ định cực kì chọn lọc bởi BS, cấm dùng nếu Hư Thoát nôn dãi tụt huyết áp).", "Chỉ dùng cho thể Nhiệt bế: tán bột pha nước ấm cho bệnh nhân uống từ từ qua xông (Sonde dạ dày) để thanh tâm giải độc, khoát đàm khai khiếu."],
  ["Hôn mê sâu xa, mắt nhắm nghiền nhược nhiếp, miệng há hốc, dãi rớt giọt, chân tay mềm nhũn lạnh toát, đổ mồ hôi đầm đìa như đầm, đại tiểu tiện vãi ra quần không biết. Mạch vi muốn tuyệt.", "Hôn mê sâu, mắt nhắm không kín, miệng há, tay chân duỗi bẵng lạnh toát, mồ hôi đầm đìa, đại tiểu tiện không tự chủ. Mạch vi muốn tuyệt."],
  ["Lý hư thoạt tột cùng", "Lý hư bạo thoát"],
  ["Cấp tốc sắc lửa to đổ cứu vớt dương khí sót lại giữ lấy sinh mệnh (Tuyệt đối không uống An cung).", "Dùng cấp cứu hồi dương cứu nghịch trong giai đoạn bạo thoát."],
  ["Sốt cao đột ngột hừng hực", "Sốt cao đột ngột"],
  ["Sốt cao bứt rứt không yên, hoặc vật vã li bì. Xuất huyết dưới da (thường ở tay, bụng, cẳng chân), hoặc chảy máu cam, chảy máu chân răng. Lưỡi đỏ sẫm hoặc tím khô rêu nứt nẻ. Mạch vi sác hoặc hư sác.", "Sốt cao, bứt rứt vật vã hoặc li bì. Xuất huyết đa dạng (dưới da, mũi, chân răng, có thể xuất huyết tiêu hoá). Chất lưỡi đỏ sẫm hoặc khô tía. Mạch hư sác."],
  ["phương gia giảm", "thang gia giảm"],
  ["Ợ hơi, ợ chua, buồn nôn, trào dịch đắng chua lên cổ. Đau quặn hoặc rát ngực thượng vị. Hay căng thẳng cáu gắt, ngủ trằn trọc. Bụng trướng. Lưỡi đỏ rêu mỏng vàng. Mạch huyền.", "Ợ hơi, ợ chua, lợm giọng buồn nôn, nóng rát thượng vị. Hay cáu gắt, ngủ kém, bụng trướng. Rêu lưỡi vàng mỏng. Mạch huyền."],
  ["Ợ hơi trong, có nước dãi nhạt. Đầy chướng bụng, ăn uống kém, mệt mỏi đuối sức. Hay đi phân lỏng nát. Rêu lưỡi trắng, bệu. Mạch hoãn nhược.", "Ợ hơi, buồn nôn ra dịch trong. Đầy trướng bụng, ăn kém chậm tiêu, người mệt mỏi yếu ớt, đại tiện lỏng. Rêu lưỡi trắng nhợt bệu. Mạch nhu hoãn."],
  ["Đau quặn bụng, đau chạy dọc theo mạng sườn lan xuống bụng dưới. Đang đau phải đi cầu ngay, đi xong thì đỡ đau. Hay bực tức lo âu. Phân lỏng nát, hoặc đầu cứng đuôi lợn cợn. Lưỡi nhạt rêu mỏng. Mạch huyền hoãn.", "Đau bụng dọc khung đại tràng, cảm giác mót rặn, đại tiện xong thì giảm đau. Bệnh liên quan stress căng thẳng. Chất phân thay đổi (lỏng nát hoặc táo táo lỏng lỏng). Rêu lưỡi nhạt mỏng. Mạch huyền hoãn."],
  ["Tình chí uất kết làm Can mộc khắc Tỳ thổ, Vị khí mất hòa giáng mà nghịch bốc lên trên (Vị khí nghịch thượng). Hoặc đàm thấp ngưng trệ gây cản trở Vị khí.", "Do yếu tố tình chí (Can khí uất kết) làm tổn thương tỷ vị, vị khí nghịch lên trên; hoặc do ẩm thực không điều độ gây tổn thương Tỳ Vị."],
  ["Đau quặn bụng, đau chạy dọc theo mạng sườn lan xuống bụng dưới.", "Đau quặn bụng dọc theo mạng sườn lan xuống bụng dưới."],
  ["phòng ngừa chứng tả lỏng trút ào ạt do nhu động ruột quá mức kích.", "chỉ thống tĩnh tràng, cầm tả do tỳ vị hư hàn, can khí uất kết."],
  ["tiểu ráo", "tiểu dầm nhiều"],
  ["Nấu sắc hoặc tán bột mài uống chiêu nước ấm.", "Làm hoàn hoặc sắc uống theo chỉ định để ôn bồ thận khí, thu liễm cố sáp."],
  ["tiểu không hết rặn yếu, tiểu dắt nhiều lần đêm, tia nước tiểu nhỏ yếu.", "tiểu khó, rặn tiểu, tiểu rắt nhiều lần đặc biệt về đêm, dòng tiểu yếu."],
  ["Tiểu rắt, tia tiểu yếu phải nhón gót rặn đau, đêm dậy đái nhiều lần nhọc. Lưng đau gối mỏi chân nhẽo lạnh, ù tai. Sắc mặt ám xỉn, lưỡi nhạt bệu tím. Mạch trầm trì sáp.", "Tiểu rắt, tia tiểu yếu, tiểu khó, đêm tiểu nhiều lần. Thắt lưng đau, gối mỏi, chi dưới lạnh nhẽo, ù tai. Sắc mặt ám tối, lưỡi nhợt bệu hoặc có điểm ứ huyết. Mạch trầm sáp hoặc trì nhược."],
  ["Uống thuốc dài ngày để vừa khai thông vừa ôn bổ thu teo khóm.", "Uống lâu ngày để bổ thận dương, hỗ trợ làm nhỏ bớt khối u phì đại, thông đường tiểu."],
  ["ngù đù lùn lại", "giảm chiều cao, còng lưng."],
  ["Đau mỏi lưng toàn thân, còng xuống. Răng rụng lung lay. Hay ớn lạnh, đi tiểu trong dài, tai ù, gối lụ khụ mỏi.", "Đau lưng mỏi gối toàn thân, còng lưng. Răng lung lay rụng sớm, ù tai, chi thể ớn lạnh, tiểu tiện trong dài."],
  ["Nấu nước cho quyện cao vào uống bổ xương dài dẳng. Không được vội vàng.", "Dùng dưới dạng sắc lỏng hoàn, bồi bồ thận tinh, cường tráng cân cốt lâu dài."],
  ["Chứng Đàm trọc nộn béo, Tỳ mất chức vạn hóa tạo ra mỡ đọng. Ẩm thực cao lương mỹ vị tịnh thấp.", "Do Tỳ vị vận hóa kém sinh Đàm thấp uẩn kết, hoặc do thói quen ăn nhiều đồ béo ngọt (cao lương mỹ vị)."],
  ["Người thường béo hình mập mạp bệu lỏng, hay mệt mỏi, nặng hai cánh tay ống chân. Đầy bụng, khó thở nhẹ, tiêu thực chậm. Lưỡi bệu ướt rêu nhờn dính. Mạch nhu trơn.", "Người thừa cân béo phì, hay mệt mỏi, nặng nề tê mỏi tay chân. Hay đầy bụng khó tiêu. Chất lưỡi bệu có dấu răng, rêu trắng nhờn dính. Mạch hoạt nhược."],
  ["Nấu nước giải khát, tăng đào thải đào trọc.", "Sắc uống hằng ngày giúp kiện tỷ hoà vị, tiêu thực hoá đàm, thông thanh giáng trọc."],
  ["Đau tức ngực mạn sườn, rát một dải, đau tăng khi hắt hơi. Ấn có điểm đau nhói giữa gai sau hoặc ấn sườn giữa.", "Đau chói lan theo dọc dây thần kinh liên sườn vùng mạng sườn, đau tăng khi thay đổi tư thế, ho hắt hơi."],
  ["Đau mạng sườn tức ngực, thích thở dài, giận dữ làm đau thắt thêm. Mạng sườn lúc đau ngấm lúc chạy, cự án nhẹ. Mạch huyền.", "Đau rát vùng sườn ngực, hay thở dài, khi giận dữ đau tăng túc lên trên. Đau có xu hướng di chuyển (đau tẩu thoái). Cự án nhẹ, Mạch huyền."],
  ["Đau cố định một chỗ nhói nhức nhối như dao kim châm. Bệnh kéo dài âm ỉ không ngớt, đêm đau nặng. Vùng da dải sườn có thể tổn thương, rát rần. Lưỡi rêu tím có nốt. Mạch sáp.", "Đau chói buốt như kim châm, đau cố định tại một chỗ dọc sườn, về đêm đau nằng nề hơn. Nếu do di chứng Zona sẽ kèm dị cảm vùng da. Chất lưỡi tím hoặc có điểm ứ huyết. Mạch sáp."],
  ["Huyết phủ trục ứ thang", "Huyết phủ trục ứ thang / Phục nguyên hoạt huyết thang"],
  ["Sắc uống tản ứ vùng ngực.", "Sắc uống, giúp sơ can lý khí định thống."],
  ["Sắc uống hoặc ngâm rượu thoa đắp bọc mút chườm.", "Sắc uống, hoặc ngâm cồn xoa bóp ngoài da dọc theo rễ sườn đau."],
  ["Não tủy chưa hoàn thiện, Tiên thiên thận khí kém cỏi bất túc mất khả năng bế tàng, hoặc Tỳ Phế khí hư hãm không thu nhiếp được thủy dịch.", "Do não tuỷ phát triển chưa hoàn thiện; hoặc tiên thiên bất túc làm Thận khí kém, Bàng quang mất chức năng bế tàng; hoặc do Tỳ Phế khí hư không nhiếp được tỷ thuỷ."],
  ["đái dài", "tiểu đêm nhiều"]
];

replacements.forEach(([search, replace]) => {
  data = data.split(search).join(replace);
});

fs.writeFileSync('src/data.ts', data);
console.log('Done rewrites.');
